apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service-dm
  namespace: springboot-kube
spec:
  selector:
    matchLabels:
      app: consumer-service
      version: V1.0.0
  replicas: 2
  template:
    metadata:
      labels:
        app: consumer-service
        version: V1.0.0
    spec:
      containers:
        - name: consumer-service
          image: local-dtr.com/kube-consumer-service:Develop
          ports:
            - containerPort: 8081
              name: http
          readinessProbe:
            httpGet:
              path: /manage/info
              # use named port
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /manage/healthcheck
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service-svc
  namespace: springboot-kube
spec:
  ports:
    - port: 80
      protocol: TCP
      # use named port, same with pod:ports:name
      targetPort: http
  selector:
    app: consumer-service
    version: V1.0.0
  sessionAffinity: None
  type: ClusterIP