apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kube-boot-ingress
  namespace: springboot-kube
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: shf.boot.com
      http:
        paths:
          - path: /producer-service/?(.*)
            backend:
              serviceName: producer-service-svc
              servicePort: 80
          - path: /consumer-service/?(.*)
            backend:
              serviceName: consumer-service-svc
              servicePort: 80
          - path: /gateway-service/?(.*)
            backend:
                serviceName: gateway-service-svc
                servicePort: 80
