apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-service-dm
  namespace: springboot-kube
spec:
  selector:
    matchLabels:
      app: producer-service
      version: V1.0.0
  replicas: 2
  template:
    metadata:
      labels:
        app: producer-service
        version: V1.0.0
    spec:
      containers:
        - name: producer-service
          image: local-dtr.com/kube-producer-service:Develop
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: producer-service-svc
  namespace: springboot-kube
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: producer-service
    version: V1.0.0
  sessionAffinity: None
  type: ClusterIP